apiVersion: v1
kind: Service
metadata:
  name: cloud-aks-dashboard-svc
  namespace: produccion
spec:
  type: LoadBalancer
  selector:
    app: cloud-aks-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000